### PR TITLE
Minor animation export bugs fixed

### PR DESCRIPTION
**Pull request by SubhadeepG**
@niftools/blender-niftools-addon-reviewer 

# Overview
Fixed two minor bugs with kf export

##  Detailed Description

- Fixed the bug where the animation start and stop times were very high
- Fixed the target name of the NiControllerSequence. Changed the target name from Scene root to NPC Root [Root]. Here the target name should be the name of the root bone of the skeleton.

## Fixes Known Issues
#420 

## Documentation
**[Overview of updates to documentation]**

## Testing
Tested the exported files using NifSkope. All the values are correct.

### Manual
**[Set of steps to manually verify updates are working correctly]**

### Automated
**[List of tests run, updated or added to avoid future regressions]**

## Additional Information
**[Anything else you deem relevant]**

### CODE REVIEW

**Comment by Ghostwalker71** [comment]
The scene root is needed for older games (fallout 3 and oblivion and previous titles) npc root works for skyrim and fallout 4. You will need to implement code that will process the roots according to the file version. Similar to what I wrote for the armature export.

**Comment by neomonkeus** [comment]
> The scene root is needed for older games (fallout 3 and oblivion and previous titles) npc root works for skyrim and fallout 4. You will need to implement code that will process the roots according to the file version. Similar to what I wrote for the armature export.

That is exactly what is implemented?

**Comment by Ghostwalker71** [comment]
It looks to me that the target name was changed from scene root to npc root rather than logic to verify version and use scene root or npc root as appropriate per file version. This will work for skyrim and later games but will cause errors in earlier games that need the scene root as the base for animations.

**Comment by SubhadeepG** [comment]
The target name was changed only for Skyrim. The changed code is inside a if statement which is only executed for skyrim. Other games are not affected,

**Review by neomonkeus — APPROVED** [review]

**Pull request merged**
