### PR TITLE
Remove trailing dots for descriptions and UI items - closes #246

### LINKED ISSUE #246: UI Registration : RNA_def_property_ui_text description ends in '.'
@niftools/blender-nif-plugin-reviewer 
## Issue Overview

Regression in UI property registration
### Blender Nif Plugin Version Info

Blender Nif Plugin v2.6.0.dev4-02-04-2016
https://www.dropbox.com/s/6r7gz3m38r83x6e/blender_nif_plugin-2.6.0a0.dev4-02.04.2016.zip?dl=0
### Blender Version Info

Blender 2.77 64bit - Default installation location
### Platform information

Ubuntu 15.04 64-bitt
## Context

We expose Niftools specific properties in the UI.
Each Property has a description member for that NiObject property.
They are exposed as tool-tips but appear to be not created correctly.
## Steps to Reproduce
1. Launch Blender from the terminal window.
## Expected Result

Startup should not contain any error messages
## Actual Result

The logs are reporting errors from misconfiguration of Property descriptions.
## Possible Fix

Remove the trailing "." from the descriptions
## Screenshot

N/A
## Logs and Files

N/A
### Info Bar Output

N/A
### Console Output

```
RNA_def_property_ui_text: 'LHMaxFriction' '' description ends with a '.' !
RNA_def_property_ui_text: 'tau' '' description ends with a '.' !
RNA_def_property_ui_text: 'damping' '' description ends with a '.' !
RNA_def_property_ui_text: 'rootnode' '' description ends with a '.' !
RNA_def_property_ui_text: 'bs_inv_x' '' description ends with a '.' !
RNA_def_property_ui_text: 'bs_inv_y' '' description ends with a '.' !
RNA_def_property_ui_text: 'bs_inv_z' '' description ends with a '.' !
RNA_def_property_ui_text: 'bs_inv_zoom' '' description ends with a '.' !
RNA_def_property_ui_text: 'bs_shadertype' '' description ends with a '.' !
RNA_def_property_ui_text: 'epsilon' '' description ends with a '.' !
RNA_def_property_ui_text: 'log_level' '' description ends with a '.' !
RNA_def_property_ui_text: 'profile_path' '' description ends with a '.' !
RNA_def_property_ui_text: 'scale_correction_import' '' description ends with a '.' !
RNA_def_property_ui_text: 'override_scene_info' '' description ends with a '.' !
RNA_def_property_ui_text: 'keyframe_file' '' description ends with a '.' !
RNA_def_property_ui_text: 'egm_file' '' description ends with a '.' !
RNA_def_property_ui_text: 'animation' '' description ends with a '.' !
RNA_def_property_ui_text: 'merge_skeleton_roots' '' description ends with a '.' !
RNA_def_property_ui_text: 'send_geoms_to_bind_pos' '' description ends with a '.' !
RNA_def_property_ui_text: 'send_detached_geoms_to_node_pos' '' description ends with a '.' !
RNA_def_property_ui_text: 'send_bones_to_bind_position' '' description ends with a '.' !
RNA_def_property_ui_text: 'apply_skin_deformation' '' description ends with a '.' !
RNA_def_property_ui_text: 'skeleton' '' description ends with a '.' !
RNA_def_property_ui_text: 'combine_shapes' '' description ends with a '.' !
RNA_def_property_ui_text: 'combine_vertices' '' description ends with a '.' !
RNA_def_struct_ui_text: 'IMPORT_SCENE_OT_nif' '' description ends with a '.' !
RNA_def_property_ui_text: 'epsilon' '' description ends with a '.' !
RNA_def_property_ui_text: 'log_level' '' description ends with a '.' !
RNA_def_property_ui_text: 'profile_path' '' description ends with a '.' !
RNA_def_property_ui_text: 'scale_correction_export' '' description ends with a '.' !
RNA_def_property_ui_text: 'game' '' description ends with a '.' !
RNA_def_property_ui_text: 'animation' '' description ends with a '.' !
RNA_def_property_ui_text: 'smooth_object_seams' '' description ends with a '.' !
RNA_def_property_ui_text: 'bs_animation_node' '' description ends with a '.' !
RNA_def_property_ui_text: 'stripify' '' description ends with a '.' !
RNA_def_property_ui_text: 'stitch_strips' '' description ends with a '.' !
RNA_def_property_ui_text: 'flatten_skin' '' description ends with a '.' !
RNA_def_property_ui_text: 'skin_partition' '' description ends with a '.' !
RNA_def_property_ui_text: 'pad_bones' '' description ends with a '.' !
RNA_def_property_ui_text: 'max_bones_per_partition' '' description ends with a '.' !
RNA_def_property_ui_text: 'max_bones_per_vertex' '' description ends with a '.' !
RNA_def_property_ui_text: 'force_dds' '' description ends with a '.' !
RNA_def_struct_ui_text: 'EXPORT_SCENE_OT_nif' '' description ends with a '.' !
```
### Blend File

N/A
### Nif File

N/A
## Similar Known Issues
#244
## Additional Information

N/A

### PR DESCRIPTION
**Pull request by HENDRIX-ZT2**
@niftools/blender-niftools-addon-reviewer 

# Overview
I think I've got them all.

##  Detailed Description
Trailing dots are no longer duplicated for UI strings.

## Fixes Known Issues
closes #246 

## Documentation
**[Overview of updates to documentation]**

## Testing
Not sure how to test it - starting from console no longer raises the warnings, at least for me.

### Manual
**[Set of steps to manually verify updates are working correctly]**

### Automated
**[List of tests run, updated or added to avoid future regressions]**

## Additional Information
**[Anything else you deem relevant]**

### CODE REVIEW

**Review by Candoran2 — COMMENTED** [review]
Any reason you also removed the trailing dot on a number of EnumProperty items? I haven't been able to show the errors for myself, but I can see when there are two dots. Best I can tell, this is not the case for item descriptions. Or is it just to keep in line with Blender's formatting?

**Comment by HENDRIX-ZT2** [comment]
> Any reason you also removed the trailing dot on a number of EnumProperty items? I haven't been able to show the errors for myself, but I can see when there are two dots. Best I can tell, this is not the case for item descriptions. Or is it just to keep in line with Blender's formatting?

When I tested, they also showed two dots.

**Comment by Candoran2** [comment]
> > Any reason you also removed the trailing dot on a number of EnumProperty items? I haven't been able to show the errors for myself, but I can see when there are two dots. Best I can tell, this is not the case for item descriptions. Or is it just to keep in line with Blender's formatting?
> 
> When I tested, they also showed two dots.

That's odd, they don't for me:
image
Anyways, it's probably best to keep with Blender's conventions regardless.

**Review by Candoran2 — APPROVED** [review]

**Comment by HENDRIX-ZT2** [comment]
grafik
They do for me on 2.93! 😅

**Comment by Candoran2** [comment]
> grafik They do for me on 2.93! 😅

Ah, I see the difference. It's when you hover over the option instead of hovering over the field. Yeah, I get two dots then as well.

**Pull request merged**
